services:
  web:
    image: marquei-web
    container_name: marquei-web
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./web:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - api
  api:
    image: marquei-api
    container_name: marquei-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
      - /app/node_modules
    command: sh start.sh
    depends_on:
      - db
    env_file:
      - ./api/.env
  db:
    image: postgres:16.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=marquei
    volumes:
      - marquei_pg_data:/var/lib/postgresql/data
  prisma-studio:
    image: marquei-prisma-studio
    build:
      context: ./prisma-studio
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://docker:docker@db:5432/marquei
    volumes:
      - ./prisma-studio:/app
      - ./api/prisma:/app/prisma
      - /app/node_modules

volumes:
  marquei_pg_data:
