# @name login
POST {{host}}/login
Content-Type: application/json

{
    "email": "sudo@marquei.com",
    "password": "LOXn4SEEcd"
}

###
@authToken = Bearer {{login.response.body.$.token}}

PATCH  {{host}}/change-password
Authorization: {{authToken}}
Content-Type: application/json

{
    "currentPassword": "senhaatual",
    "newPassword": "senhanova",
    "repeatPassword": "repetirsenhanova"
}