# @name login
POST {{host}}/login
Content-Type: application/json

{
    "email": "adminGisele02@email.com",
    "password": "1nz18nBhR5"
}

###

@authToken = {{login.response.body.$.token}}

PATCH {{host}}/change-password
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "newPassword": "12345678",
    "repeatPassword": "12345678"
}
