# @name login
POST {{host}}/auth/login
Content-Type: application/json

{
    "email": "sudo@marquei.com",
    "password": "1234567890"
}

###

@auth_token = {{login.response.body.$.token}}

POST {{host}}/profiles
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "name": "user da silva 2",
    "email": "user2@silva.com",
    "occupation": "developer",
    "level": "USER",
    "companyId": 1
}