# @name login
POST {{host}}/login
Content-Type: application/json

{
    "email": "admin@marquei.com",
    "password": "1234567890"
}

###

@authToken = {{login.response.body.$.token}}

POST {{host}}/profiles
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "User da Silva",
    "occupation": "Recepcionista",
    "email": "userdasilva@email.com",
    "level": "ADMIN",
    "companyId": 1
}
