# @name login
POST {{host}}/login
Content-Type: application/json

{
    "email": "sudoGisele@marquei.com",
    "password": "UHU31zqmv7"
}

###

@authToken = Bearer {{login.response.body.$.token}}

POST {{host}}/profiles
Content-Type: application/json
Authorization: {{authToken}}

{
    "name": "Admin 01",
    "occupation": "Gerente",
    "email": "admin01@marquei.com",
    "level": "ADMIN",
    "companyId": 1
}
