# @name login
POST {{host}}/auth/login
Content-Type: application/json

{
    "email": "sudo@marquei.com",
    "password": "1234567890"
}

###

@profile_id = 12
@auth_token = {{login.response.body.$.token}}

PATCH {{host}}/profiles/deactivate/{{profile_id}}
Authorization: Bearer {{auth_token}}