# @name login
POST {{host}}/login
Content-Type: application/json

{
    "email": "shea99@yahoo.com",
    "password": "1234567890"
}

###
@authToken = Bearer {{login.response.body.$.token}}

PATCH  {{host}}/profile/deactivate/32
Authorization: {{authToken}}
