# @name login
POST {{host}}/login
Content-Type: application/json

{
    "email": "sudoGisele@marquei.com",
    "password": "UHU31zqmv7"
}

###

@authToken = Baerer {{login.response.body.$.token}}

POST {{host}}/sudo-login
Authorization: {{authToken}}
Content-Type: application/json

{
    "email": "admindasilva@email.com"
}
