# @name reset_password
POST {{host}}/reset-password
content-Type: application/json

{
    "email": "sudo@marquei.com"
}

###
@token = {{reset_password.response.body.$.token}}

PATCH {{host}}/create-new-password
content-Type: application/json

{
    "password": "1234567890",
    "repeatPassword": "1234567890",
    "token": {{token}}
}