# @name login
POST {{host}}/auth/login
Content-Type: application/json

{
    "email": "user@marquei.com",
    "password": "1234567890"
}

###

@auth_token = {{login.response.body.$.token}}

POST {{host}}/resources
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "name": "Dr. Hudson Dodói",
    "description": "Ortopedista",
    "categoryId": 1,
    "companyId": 1
}
