# @name reset_password_token
POST {{host}}/auth/reset-password-token
Content-Type: application/json

{
    "email": "sudo@marquei.com"
}

###

@password_reset_token = {{reset_password_token.response.body.$.token}}

POST {{host}}/auth/reset-password
Content-Type: application/json

{
    "token": "{{password_reset_token}}",
    "newPassword": "0987654321",
    "repeatPassword": "0987654321"
}