# @name login
POST {{host}}/login
Content-Type: application/json

{
    "email": "userdasilva@email.com",
    "password": "gTQ2k9Xm2e"
}

###

@authToken = Bearer {{login.response.body.$.token}}

POST {{host}}/categories
Content-Type: application/json
Authorization: {{authToken}}

{
    "name": "Médicos",
    "companyId": 1
}
